# Generated by Django 4.1.4 on 2023-01-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='gende',
            new_name='gender',
        ),
    ]
