# Generated by Django 4.1.4 on 2023-01-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_gende_students_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
    ]
