# Generated by Django 4.1.4 on 2023-01-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applyDate', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.students')),
            ],
        ),
    ]
